version: "3.7"

services:

    pdf:
        image: openlabs/docker-wkhtmltopdf
        volumes: 
            - .:/data
        command: --viewport-size 1920x1920 --zoom 0.4 /data/pdf.html /data/cv.pdf

    www:
        image: httpd:2.4
        restart: on-failure:3
        volumes:
            - .:/usr/local/apache2/htdocs/
        networks: 
            - docker-net
        ports:
            - 80:80

networks:
    docker-net:
        name: docker-net
        external: false
