version: "3.8"

services:

    www:
        image: httpd:2.4
        restart: on-failure:3
        volumes:
            - .:/usr/local/apache2/htdocs/
        networks: 
            - docker-net
        ports:
            - 80:80

networks:
    docker-net:
        name: docker-net
        external: false
